spring.application.name=eScape
spring.devtools.restart.enabled=true
spring.datasource.url= jdbc:postgresql://localhost:5432/ESCAPE
spring.datasource.username=postgres
spring.datasource.password=ha3072003
