spring.application.name=eScape
spring.devtools.restart.enabled=true
mybatis.mapper-locations=classpath:db/mybatis/*.xml
mybatis.type-aliases-package=com.example.eScape.model,com.example.eScape.dto
spring.datasource.url= jdbc:postgresql://localhost:5432/ESCAPE
spring.datasource.username=postgres
spring.datasource.password=ha3072003
